import { existsSync, readFileSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { matchAny, walk } from './glob.ts';
import {
  computedClaim,
  crossReference,
  filenameSchema,
  gitStatusReconcile,
  idIntegrity,
  registerSchema,
  renderFreshness,
} from './engines2.ts';

export interface Finding {
  file?: string;
  message: string;
}
export interface EngineResult {
  findings: Finding[];
  /** What the engine looked at. A gate that examined nothing is not a passing gate. */
  examined: number;
}
export type Engine = (table: any, repoRoot: string, files: string[]) => EngineResult;

const read = (root: string, rel: string) => {
  try {
    return readFileSync(join(root, rel), 'utf8');
  } catch {
    return '';
  }
};

/**
 * `expand` also drops anything the CLI generated.
 *
 * Without it a gate fires on its own tool's output: `render` degrades a
 * path-scoped rule into a nested `docs/plans/AGENTS.md` for harnesses with no
 * glob scoping, and the `workflows` gate — which scans `docs/plans/**` for plan
 * documents — then reported that file for having no plan frontmatter. The
 * render pipeline and the gate scopes collide by construction, so the exclusion
 * is global rather than per-table: **a gate must never fire on a file rungs
 * wrote.**
 */
const GENERATED = 'Generated by `rungs';

const expand = (files: string[], patterns: string[] | undefined, fallback: string[] = []) =>
  [...new Set((patterns ?? fallback).flatMap((p) => matchAny(files, p)))];

function dropGenerated(root: string, rels: string[]): string[] {
  return rels.filter((rel) => !read(root, rel).slice(0, 600).includes(GENERATED));
}

/** Lines that actually load: HTML comments are stripped by at least one harness. */
function loadedLines(text: string): number {
  return text
    .replace(/^---\n[\s\S]*?\n---\n/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .split('\n')
    .filter((l) => l.trim()).length;
}

const fileBudget: Engine = (t, root, files) => {
  const targets = dropGenerated(root, t.file ? [t.file] : expand(files, t.scan));
  const excluded = new Set(expand(files, t.exclude, []));
  const findings: Finding[] = [];
  let examined = 0;
  for (const rel of targets) {
    if (excluded.has(rel) || !existsSync(join(root, rel))) continue;
    examined++;
    const n = loadedLines(read(root, rel));
    if (n > t.max_lines) findings.push({ file: rel, message: `${n} lines, budget ${t.max_lines}` });
  }
  return { findings, examined };
};

const sections: Engine = (t, root, files) => {
  const specs = Array.isArray(t) ? t : [t];
  const findings: Finding[] = [];
  let examined = 0;
  for (const spec of specs) {
    const targets = dropGenerated(root, spec.file ? [spec.file] : expand(files, spec.scan));
    const excluded = new Set(expand(files, spec.exclude, []));
    for (const rel of targets) {
      if (excluded.has(rel) || !existsSync(join(root, rel))) continue;
      examined++;
      const text = read(root, rel);
      const heads = [...text.matchAll(/^#{1,6}\s+(.+?)\s*$/gm)].map((m) => m[1]);
      for (const want of spec.required ?? []) {
        const idx = heads.findIndex((h) => h.toLowerCase().startsWith(String(want).toLowerCase()));
        if (idx === -1) {
          findings.push({ file: rel, message: `missing section '${want}'` });
          continue;
        }
        if (spec.non_empty) {
          const after = text.split(new RegExp(`^#{1,6}\\s+${escapeRe(heads[idx])}\\s*$`, 'm'))[1] ?? '';
          const body = after.split(/^#{1,6}\s+/m)[0].replace(/<!--[\s\S]*?-->/g, '').trim();
          if (!body) findings.push({ file: rel, message: `section '${want}' is empty` });
        }
      }
      for (const open of spec.requires_opening ?? []) {
        if (!text.slice(0, 400).includes(open)) findings.push({ file: rel, message: `does not open with ${open}` });
      }
    }
  }
  return { findings, examined };
};

const frontmatterSchema: Engine = (t, root, files) => {
  const specs = Array.isArray(t) ? t : [t];
  const findings: Finding[] = [];
  let examined = 0;
  for (const spec of specs) {
    for (const rel of dropGenerated(root, expand(files, spec.scan))) {
      if (new Set(expand(files, spec.exclude, [])).has(rel)) continue;
      const text = read(root, rel);
      const m = text.match(/^---\n([\s\S]*?)\n---/);
      if (!m) {
        findings.push({ file: rel, message: 'no frontmatter' });
        continue;
      }
      examined++;
      const keys = [...m[1].matchAll(/^([a-zA-Z0-9_-]+):/gm)].map((k) => k[1]);
      for (const req of spec.required ?? []) {
        if (!keys.includes(req)) findings.push({ file: rel, message: `missing '${req}'` });
      }
      if (spec.allowed) {
        for (const k of keys) {
          if (!spec.allowed.includes(k)) findings.push({ file: rel, message: `non-spec key '${k}'` });
        }
      }
      for (const [key, values] of Object.entries(spec.enum ?? {})) {
        const v = m[1].match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))?.[1].trim().replace(/^["']|["']$/g, '');
        if (v && !(values as string[]).map(String).includes(v)) {
          findings.push({ file: rel, message: `${key}='${v}' not one of ${(values as string[]).join(', ')}` });
        }
      }
    }
  }
  return { findings, examined };
};

const linkIntegrity: Engine = (t, root, files) => {
  const scan = expand(files, t.scan, ['**/*.md']);  // link checks DO cover generated files
  const excluded = new Set(expand(files, t.exclude, []));
  const findings: Finding[] = [];
  let examined = 0;
  for (const rel of scan) {
    if (excluded.has(rel)) continue;
    examined++;
    const text = read(root, rel);
    if (/path-ok:\s*\S/.test(text)) continue;
    for (const m of text.matchAll(/\]\((?!https?:|#|mailto:)([^)\s#]+)/g)) {
      const target = resolve(root, dirname(rel), decodeURIComponent(m[1]));
      if (!existsSync(target)) findings.push({ file: rel, message: `broken link → ${m[1]}` });
    }
  }
  return { findings, examined };
};

const filePopulation: Engine = (t, root, files) => {
  const hits = dropGenerated(root, expand(files, t.scan)).filter((f) => !new Set(expand(files, t.exclude, [])).has(f));
  const findings: Finding[] = [];
  const failAt = t.fail_at ?? Infinity;
  if (hits.length >= failAt) {
    findings.push({ message: `${hits.length} matching files, threshold ${failAt} (e.g. ${hits[0]})` });
  }
  return { findings, examined: hits.length };
};

/**
 * The meta-gate: every declared gate must carry a self-test expecting `pass`
 * and one expecting `fail`. A gate whose rules are all currently satisfied is
 * indistinguishable from a gate that matches nothing.
 */
const gateMeta: Engine = (_t, root) => {
  const findings: Finding[] = [];
  const registry = join(root, '.ai', 'gates.toml');
  if (!existsSync(registry)) return { findings, examined: 0 };
  const text = readFileSync(registry, 'utf8');
  const entries = [...text.matchAll(/\[\[gates\]\][\s\S]*?(?=\n\[\[gates\]\]|\n# rungs:end|$)/g)].map((m) => m[0]);
  let examined = 0;
  for (const entry of entries) {
    const id = entry.match(/^id\s*=\s*"(.+)"/m)?.[1];
    const kind = entry.match(/^kind\s*=\s*"(.+)"/m)?.[1];
    const table = entry.match(/^table\s*=\s*"(.+)"/m)?.[1];
    if (!id || kind !== 'declared' || !table) continue;
    examined++;
    // Tables live in the CLI, not the repo, so read them from the module set.
    const tablePath = join(dirname(new URL(import.meta.url).pathname.slice(1)), '..', 'modules', dirname(table), 'gates', table.split('/').pop()!);
    const src = existsSync(tablePath) ? readFileSync(tablePath, 'utf8') : '';
    const forGate = [...src.matchAll(/\[\[self_test\]\][\s\S]*?(?=\n\[\[|\n\[|$)/g)]
      .map((m) => m[0])
      .filter((b) => b.includes(`gate   = "${id}"`) || b.includes(`gate    = "${id}"`) || b.includes(`gate = "${id}"`));
    for (const direction of ['pass', 'fail']) {
      if (!forGate.some((b) => new RegExp(`expect\\s*=\\s*"${direction}"`).test(b))) {
        findings.push({ message: `gate '${id}' has no self-test expecting '${direction}'` });
      }
    }
  }
  return { findings, examined };
};

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export const ENGINES: Record<string, Engine> = {
  'file-budget': fileBudget,
  sections,
  'frontmatter-schema': frontmatterSchema,
  'link-integrity': linkIntegrity,
  'file-population': filePopulation,
  'gate-meta': gateMeta,
  'id-integrity': idIntegrity,
  'render-freshness': renderFreshness,
  'register-schema': registerSchema,
  'filename-schema': filenameSchema,
  'cross-reference': crossReference,
  'git-status-reconcile': gitStatusReconcile,
  'computed-claim': computedClaim,
};

/**
 * Engines named in a gate table but not implemented here. Reported by name and
 * treated as blocking — never as a pass.
 *
 * This is the single most dangerous failure this tool could have: a registry of
 * 31 gates reporting green because 25 of them do nothing. rift-forge's rule
 * generalises exactly — *we do not land on an unknown.*
 */
export function isImplemented(engine: string): boolean {
  return engine in ENGINES;
}
