import { existsSync, readFileSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { matchAny, walk } from './glob.ts';
import { parse as parseToml } from 'smol-toml';
import { runSelfTests } from './selftest.ts';
import { loadAllModules } from './manifest.ts';

import { resolveParams, substitute } from './substitute.ts';
import {
  computedClaim,
  crossReference,
  changeRequiresFile,
  filenameSchema,
  gitStatusReconcile,
  idIntegrity,
  registerSchema,
  renderFreshness,
  selfDeclaredClosure,
} from './engines2.ts';
import { boardReconcile, changelogFreshness, gitState, mergeDriverCheck, rulePropagation, termOwnership } from './engines3.ts';
import { selectEngineTable } from './engine-table.ts';

/**
 * Where the CLI's own `modules/` lives.
 *
 * This was `new URL(import.meta.url).pathname.slice(1)` in three places. The
 * `.slice(1)` strips a leading `/`, which is right on Windows — `/C:/…` becomes
 * `C:/…` — and **wrong everywhere else**, where `/home/runner/…` becomes the
 * relative `home/runner/…`. On Linux and macOS the directory did not resolve,
 * `loadAllModules` found nothing, and three gates silently lost the data they
 * read from the module set: `skills-spec-pure` and `skills-description-routes`
 * reported every opted-in extension as a non-spec key, and
 * `gates-self-tests-both-directions` reported gates that have fixtures as
 * having none. All three passed here and failed on the first Linux run (F-036).
 *
 * `fileURLToPath` is what the rest of the codebase already used.
 */
const CLI_MODULES = join(dirname(fileURLToPath(import.meta.url)), '..', 'modules');

export interface Finding {
  file?: string;
  message: string;
  /** Stable comparison form when the displayed diagnostic carries environment-specific detail. */
  identity?: string;
}
export interface EngineResult {
  findings: Finding[];
  /** What the engine looked at. A gate that examined nothing is not a passing gate. */
  examined: number;
}
export type Engine = (table: any, repoRoot: string, files: string[]) => EngineResult;

const read = (root: string, rel: string) => {
  try {
    return readFileSync(join(root, rel), 'utf8');
  } catch {
    return '';
  }
};

/**
 * `expand` also drops anything the CLI generated.
 *
 * Without it a gate fires on its own tool's output: `render` degrades a
 * path-scoped rule into a nested `docs/plans/AGENTS.md` for harnesses with no
 * glob scoping, and the `workflows` gate — which scans `docs/plans/**` for plan
 * documents — then reported that file for having no plan frontmatter. The
 * render pipeline and the gate scopes collide by construction, so the exclusion
 * is global rather than per-table: **a gate must never fire on a file rungs
 * wrote.**
 */
const GENERATED = 'Generated by `rungs';

const expand = (files: string[], patterns: string[] | undefined, fallback: string[] = []) =>
  [...new Set((patterns ?? fallback).flatMap((p) => matchAny(files, p)))];

function dropGenerated(root: string, rels: string[]): string[] {
  return rels.filter((rel) => !read(root, rel).slice(0, 600).includes(GENERATED));
}

/** Lines that actually load: HTML comments are stripped by at least one harness. */
function loadedLines(text: string): number {
  return text
    .replace(/^---\n[\s\S]*?\n---\n/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .split('\n')
    .filter((l) => l.trim()).length;
}

const fileBudget: Engine = (t, root, files) => {
  const targets = dropGenerated(root, t.file ? [t.file] : expand(files, t.scan));
  const excluded = new Set(expand(files, t.exclude, []));
  const findings: Finding[] = [];
  let examined = 0;
  for (const rel of targets) {
    if (excluded.has(rel) || !existsSync(join(root, rel))) continue;
    examined++;
    const n = loadedLines(read(root, rel));
    // "1358 lines" invites `wc -l`, which answered 1413 on the same file
    // (hexguard-templates, 2026-08-16) because this counts what actually *loads*
    // — frontmatter, HTML comments and blank lines stripped. Naming the measure
    // is the difference between evidence and a number the reader disproves.
    if (n > t.max_lines) {
      findings.push({ file: rel, message: `${n} loaded lines (blank lines and comments excluded), budget ${t.max_lines}` });
    }
  }
  return { findings, examined };
};

const sections: Engine = (t, root, files) => {
  const specs = Array.isArray(t) ? t : [t];
  const findings: Finding[] = [];
  let examined = 0;
  for (const spec of specs) {
    const targets = dropGenerated(root, spec.file ? [spec.file] : expand(files, spec.scan));
    const excluded = new Set(expand(files, spec.exclude, []));
    for (const rel of targets) {
      if (excluded.has(rel) || !existsSync(join(root, rel))) continue;
      examined++;
      const text = read(root, rel);
      const matches = [...text.matchAll(/^(#{1,6})\s+(.+?)\s*$/gm)];
      const heads = matches.map((m) => m[2]);
      for (const want of spec.required ?? []) {
        const idx = heads.findIndex((h) => h.toLowerCase().startsWith(String(want).toLowerCase()));
        if (idx === -1) {
          findings.push({ file: rel, message: `missing section '${want}'` });
          continue;
        }
        if (spec.non_empty) {
          // Content runs to the next heading of the **same or higher** level, so
          // a section made of subsections is not empty. Splitting on any heading
          // reported ADR-0002's `## Decision` as empty because a `### (a)`
          // follows it immediately — the first finding this gate produced, and a
          // false one (F-018). A section whose whole body is subsections is the
          // normal shape for a long decision.
          const level = matches[idx][1].length;
          const after = text.slice(matches[idx].index! + matches[idx][0].length);
          const body = after
            .split(new RegExp(`^#{1,${level}}\\s+`, 'm'))[0]
            .replace(/<!--[\s\S]*?-->/g, '')
            .trim();
          if (!body) findings.push({ file: rel, message: `section '${want}' is empty` });
        }
      }
      for (const open of spec.requires_opening ?? []) {
        if (!text.slice(0, 400).includes(open)) findings.push({ file: rel, message: `does not open with ${open}` });
      }
    }
  }
  return { findings, examined };
};

export const frontmatterSchema: Engine = (t, root, files) => {
  const specs = Array.isArray(t) ? t : [t];
  const findings: Finding[] = [];
  let examined = 0;
  for (const spec of specs) {
    for (const rel of dropGenerated(root, expand(files, spec.scan))) {
      if (new Set(expand(files, spec.exclude, [])).has(rel)) continue;
      const text = read(root, rel);
      const m = text.match(/^---\n([\s\S]*?)\n---/);
      if (!m) {
        findings.push({ file: rel, message: 'no frontmatter' });
        continue;
      }
      examined++;
      const keys = [...m[1].matchAll(/^([a-zA-Z0-9_-]+):/gm)].map((k) => k[1]);
      for (const req of spec.required ?? []) {
        if (!keys.includes(req)) findings.push({ file: rel, message: `missing '${req}'` });
      }
      if (spec.allowed) {
        // `extensions_allowed_from` names the manifest that may legalise a
        // non-spec key. It was declared in the skills table and read nowhere
        // (F-019), so an extension a module had deliberately opted into was
        // indistinguishable from one somebody typed by mistake — and the
        // portability cost the opt-in exists to record was attached to nothing.
        const optedIn = spec.extensions_allowed_from ? optedInExtensions(rel, spec) : new Set<string>();
        for (const k of keys) {
          if (spec.allowed.includes(k) || optedIn.has(k)) continue;
          findings.push({ file: rel, message: `non-spec key '${k}'` });
        }
      }
      const field = (k: string) => m[1].match(new RegExp(`^${k}:\\s*(.+)$`, 'm'))?.[1].trim().replace(/^["']|["']$/g, '');
      for (const [key, values] of Object.entries(spec.enum ?? {})) {
        const v = field(key);
        if (v && !(values as string[]).map(String).includes(v)) {
          findings.push({ file: rel, message: `${key}='${v}' not one of ${(values as string[]).join(', ')}` });
        }
      }

      // `[frontmatter_schema.reciprocal]` was configured in the `adr` table and
      // implemented nowhere — the third instance of F-007's shape, and this one
      // was found by *executing* a self-test rather than by reading (F-018).
      // Its fail fixture is a `superseded` record with no `superseded_by`, which
      // could never have failed while nothing read the rule.
      //
      // A one-way supersession leaves a reader on the stale record with no route
      // to the live one, which is the whole point of recording it.
      for (const pair of spec.reciprocal?.pairs ?? []) {
        const from = field(pair.from);
        if (!from) continue;
        const target = expand(files, spec.scan).find((r) => r.includes(from.replace(/\.md$/, '')));
        if (!target) {
          findings.push({ file: rel, message: `${pair.from} names '${from}', which is not a record here` });
          continue;
        }
        const back = read(root, target).match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';
        const id = field('id') ?? '';
        if (!new RegExp(`^${pair.to}:\\s*.*${escapeRe(id)}`, 'm').test(back)) {
          findings.push({ file: rel, message: `${pair.from} → ${from}, but it does not name this record back in '${pair.to}'` });
        }
      }
      // A status that implies the pairing must actually carry it.
      for (const [status, requires] of Object.entries(spec.reciprocal?.required_when ?? {})) {
        if (field('status') === status && !field(String(requires))) {
          findings.push({ file: rel, message: `status is '${status}' but '${requires}' is absent` });
        }
      }
    }
  }
  return { findings, examined };
};

/**
 * Does a link target resolve, under any reading of it?
 *
 * `path/to/file.ts:387` is a code reference, not a broken link — it is the form
 * `CLAUDE.md` mandates in this repo ("Reference code as `file_path:line_number`")
 * and the form editors and terminals click. The engine resolved it literally and
 * reported the file missing while the file sat exactly there.
 *
 * Measured 2026-08-16 on `rift-forge` via `doctor --explain`: **1,794 of 3,851
 * link findings — 46.6% — were this**, every one a real file with a line number
 * after it. Latent since WI-008 made link checking per-link; before that, one
 * `{{token}}` anywhere in a file exempted every link in it, which hid it.
 *
 * Resolve as written first, and only then retry without a trailing `:line` or
 * `:line:col`. Strip-and-retest rather than strip-and-assume: a link is called
 * broken only when **no** reading of it resolves, so this can only ever remove
 * findings. Stripping unconditionally would silence a genuinely missing
 * `foo.ts:12` whenever an equally missing `foo.ts` explained it away.
 */
function resolvesHere(root: string, rel: string, href: string): boolean {
  const from = dirname(rel);
  const decoded = decodeURIComponent(href);
  if (existsSync(resolve(root, from, decoded))) return true;
  const stripped = decoded.replace(/:\d+(?::\d+)?$/, '');
  return stripped !== decoded && existsSync(resolve(root, from, stripped));
}

/**
 * A backticked path in an instruction file — `docs/backlog/BACKLOG.md` — that no
 * longer exists. F-007: `backticked_paths` was named in the table's `check` list
 * and implemented nowhere, so `gates-paths-exist` silently ran the markdown-link
 * scan instead and reported every finding a second time.
 *
 * Resolved from the **repo root**, because that is what an instruction file's
 * reader does with a path it is told to go and read. Skipped when the span is a
 * glob, a template token, a URL, or has no path shape at all: prose is full of
 * `identifiers`, and a gate that refuses every code span is one people delete.
 */
function backtickedPaths(rel: string, text: string, root: string, hints: string[]): Finding[] {
  const out: Finding[] = [];
  const seen = new Set<string>();
  for (const m of text.matchAll(/`([^`\n]+)`/g)) {
    const raw = m[1].trim();
    if (seen.has(raw) || !hints.some((h) => raw.includes(h))) continue;
    seen.add(raw);

    // Every exclusion below is a measured false positive from the first run of
    // this check against this repo, 2026-08-16 — which produced ten findings,
    // all ten wrong. The table's own instruction is that under-detection is the
    // correct bias, so the shape is narrowed to the incident it was written for:
    // hexguard's instruction files naming a **repo-relative file** that moved.
    if (raw.startsWith('/')) continue; //            `/work-item` — a skill invocation
    if (/[*?{}#\s]|^\w+:/.test(raw)) continue; //    globs, `WI-###` placeholders, prose, URLs
    if (!raw.includes('/')) continue; //             `work-items.md` — a bare name, anchor unknown
    if (!/\.[a-z0-9]{1,5}$/i.test(raw)) continue; // `.cursor/rules/` — a directory, often illustrative

    // Two anchors, because instruction files use both: repo-root paths for "go
    // read this", and `../` paths relative to the file itself.
    const bare = raw.replace(/^\.\//, '');
    if (!existsSync(join(root, bare)) && !existsSync(resolve(root, dirname(rel), bare))) {
      out.push({ message: `stale path in a code span → ${raw}` });
    }
  }
  return out;
}

export const linkIntegrity: Engine = (t, root, files) => {
  // The table is now one entry per gate (F-007). The runner hands an array
  // through when it selects by id; take the single entry it selected.
  if (Array.isArray(t)) t = t[0] ?? {};
  const checks: string[] = t.check ?? ['relative_markdown_links'];
  const scan = expand(files, t.scan, ['**/*.md']);  // link checks DO cover generated files
  const excluded = new Set(expand(files, t.exclude, []));
  const findings: Finding[] = [];
  let examined = 0;
  for (const rel of scan) {
    if (excluded.has(rel)) continue;
    const text = read(root, rel);
    examined++;
    if (/path-ok:\s*\S/.test(text)) continue;
    if (checks.includes('backticked_paths')) {
      findings.push(...backtickedPaths(rel, text, root, t.path_hint ?? ['/']).map((f) => ({ ...f, file: rel })));
    }
    if (!checks.includes('relative_markdown_links')) continue;
    // A link written inside a code span is prose *quoting* a link — most often a document
    // explaining that some link is wrong. Blanked rather than removed, so every offset after it
    // is unchanged and the reported text still matches what the author sees.
    const scannable = text.replace(/`+[^`\n]*`+/g, (s) => ' '.repeat(s.length));
    for (const m of scannable.matchAll(/\]\((?!https?:|#|mailto:)([^)\s#]+)/g)) {
      // An unsubstituted placeholder makes a **template** link, which resolves only once
      // installed. This test used to sit on the whole file, and one token anywhere in a document
      // exempted every link in it: 16 non-excluded files, including eight that ship to consumer
      // repos, silently stopped being checked. A green gate and a skipped file looked identical.
      // The case the file-level skip was written for — `modules/*/fragments/AGENTS.md` linking
      // `{{path}}/README.md` — is already excluded by path in `link_integrity.exclude` (WI-008).
      if (/\{\{[a-z_.]+\}\}/.test(m[1])) continue;
      if (!resolvesHere(root, rel, m[1])) findings.push({ file: rel, message: `broken link → ${m[1]}` });
    }
  }
  return { findings, examined };
};

const filePopulation: Engine = (t, root, files) => {
  let hits = dropGenerated(root, expand(files, t.scan)).filter((f) => !new Set(expand(files, t.exclude, [])).has(f));

  // A `detect` narrows the population to files matching a shape. Without it the
  // gate counted *every scanned file* — so the redirect-stub check reported
  // "12 matching files, threshold 1" against a repo with no stubs at all, which
  // is a confidently wrong number rather than a finding.
  if (t.detect === 'body_is_only_a_pointer') {
    hits = hits.filter((rel) => {
      const body = read(root, rel)
        .replace(/^---\n[\s\S]*?\n---\n/, '')
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/^#.*$/gm, '')
        .trim();
      const words = body.split(/\s+/).filter(Boolean).length;
      const links = (body.match(/\]\(/g) ?? []).length;
      // Short *and* mostly a link. Short alone is a stub-shaped index page.
      return words > 0 && words <= (t.max_body_words ?? 40) && links >= 1;
    });
  }

  const findings: Finding[] = [];
  const failAt = t.fail_at ?? Infinity;
  if (hits.length >= failAt) {
    // The count is only re-derivable if the reader knows what was counted.
    // `audit-output-is-rows` reported 275 on hexguard while the obvious
    // one-pattern `find` answered 268 (2026-08-16) — the gate scans three
    // patterns, and the message named none of them, so the correct number read
    // as a wrong one.
    const scanned = [t.scan ?? []].flat();
    findings.push({
      message:
        `${hits.length} matching file(s), threshold ${failAt} (e.g. ${hits[0]})` +
        (scanned.length ? ` — matched against ${scanned.join(', ')}` : ''),
    });
  }
  return { findings, examined: hits.length };
};

/**
 * The meta-gate: every declared gate must carry a self-test expecting `pass`
 * and one expecting `fail`. A gate whose rules are all currently satisfied is
 * indistinguishable from a gate that matches nothing.
 */
export const gateMeta: Engine = (_t, root) => {
  const findings: Finding[] = [];

  let unrun = 0;

  const registry = join(root, '.ai', 'gates.toml');
  if (!existsSync(registry)) return { findings, examined: 0 };
  const text = readFileSync(registry, 'utf8');
  const entries = [...text.matchAll(/\[\[gates\]\][\s\S]*?(?=\n\[\[gates\]\]|\n# rungs:end|$)/g)].map((m) => m[0]);
  let examined = 0;
  for (const entry of entries) {
    const id = entry.match(/^id\s*=\s*"(.+)"/m)?.[1];
    const kind = entry.match(/^kind\s*=\s*"(.+)"/m)?.[1];
    const table = entry.match(/^table\s*=\s*"(.+)"/m)?.[1];
    if (!id || kind !== 'declared' || !table) continue;
    examined++;
    // Tables live in the CLI, not the repo, so read them from the module set.
    const tablePath = join(CLI_MODULES, dirname(table), 'gates', table.split('/').pop()!);
    const src = existsSync(tablePath) ? readFileSync(tablePath, 'utf8') : '';
    const forGate = [...src.matchAll(/\[\[self_test\]\][\s\S]*?(?=\n\[\[|\n\[|$)/g)]
      .map((m) => m[0])
      .filter((b) => b.includes(`gate   = "${id}"`) || b.includes(`gate    = "${id}"`) || b.includes(`gate = "${id}"`));
    for (const direction of ['pass', 'fail']) {
      if (!forGate.some((b) => new RegExp(`expect\\s*=\\s*"${direction}"`).test(b))) {
        findings.push({ message: `gate '${id}' has no self-test expecting '${direction}'` });
      }
    }

    // WI-045 / F-018: declaring is not asserting. Every fixture whose shape and
    // engine can be reproduced faithfully is executed, and a disagreement is a
    // finding of this gate.
    //
    // Turning this on found, in order: `adr`'s orphaned `[sections]` table, two
    // fixtures labelled for a gate that checks something else, a `reciprocal`
    // rule read by nothing, a `non_empty` check that called any section with
    // subsections empty, three fixtures orphaned by a schema that moved modules,
    // `session-sections-present` wired to an engine whose table it does not have
    // (so it passed by examining nothing), `[register_schema.open]` read by
    // nothing, and a table matcher loose enough that "resolve-open-findings" in
    // a filename made a Closed section match the Open schema.
    //
    // None of it was visible while the fixtures were documentation.
    const engine = entry.match(/^engine\s*=\s*"(.+)"/m)?.[1];
    const parsed = parseTable(tablePath, table.split('/')[0]);
    if (engine && parsed) {
      const blocks = (Array.isArray(parsed.self_test) ? parsed.self_test : [])
        .filter((b: any) => b?.gate === id)
        .map((b: any) => ({ expect: String(b.expect), input: b.input, fixture: b.fixture }));
      try {
        const section = selectEngineTable(parsed, engine, id);
        for (const r of runSelfTests(id, engine, section, blocks)) {
          if (r.outcome === 'mismatch') findings.push({ message: `self-test for '${id}' ${r.detail}` });
          else if (r.outcome === 'unrun') unrun++;
        }
      } catch (e: any) {
        findings.push({ message: `gate '${id}' table dispatch failed: ${e.message}` });
      }
    }
  }

  // Stated, never silent. Most fixtures still cannot be reproduced — their
  // shapes need context the format does not carry — and reporting green while
  // most of the suite never executed would be F-006 one level up. A note rather
  // than a failure: an unbuildable fixture is not a defect in the gate.
  if (unrun) console.error(`      ${unrun} self-test fixture(s) have no builder and did not run — not passes (F-018)`);
  return { findings, examined };
};

/**
 * Which non-spec frontmatter keys are legal for this skill, because the module
 * that ships it opted in.
 *
 * The skill's name is its directory — `.claude/skills/work-item/SKILL.md` — and
 * the answer lives in whichever module declares `[skills.work-item]`. Read from
 * the CLI's module set rather than from the repo, so a consumer cannot legalise
 * an extension by editing a file: the opt-in belongs to the module that took the
 * portability cost.
 *
 * `extensions_opted_in` overrides it, which is how a self-test fixture states
 * the opt-in without needing a module on disk.
 */
function optedInExtensions(rel: string, spec: any): Set<string> {
  if (Array.isArray(spec.extensions_opted_in)) return new Set(spec.extensions_opted_in.map(String));
  const name = rel.split('/').slice(-2)[0];
  if (!name) return new Set();
  try {
    const mods = loadAllModules(CLI_MODULES);
    const owner = mods.find((m) => m.skills?.[name]?.extensions);
    return new Set(Object.keys(owner?.skills?.[name]?.extensions ?? {}));
  } catch {
    return new Set();
  }
}

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * A gate table, parsed. Substitution is deliberately *not* applied: a fixture's
 * `{{token}}` is part of what it asserts, and the runner needs the table's raw
 * shape rather than one repo's resolved parameters.
 */
function parseTable(path: string, module: string): any | null {
  if (!existsSync(path)) return null;
  try {
    // Substituted with the module's **real defaults**, not a placeholder. Using
    // `probe` turned the skills schema's scan into `probe/**/SKILL.md` while its
    // fixture still wrote `.claude/skills/x/SKILL.md`, so the engine saw no file
    // and the runner reported the gate broken — a mismatch entirely of the
    // harness's making. A fixture and the table it tests must resolve against
    // the same parameters or neither means anything.
    const mods = loadAllModules(CLI_MODULES);
    const params = resolveParams(mods, {}, '.');
    return parseToml(substitute(readFileSync(path, 'utf8'), module, params));
  } catch {
    return null;
  }
}

export const ENGINES: Record<string, Engine> = {
  'file-budget': fileBudget,
  sections,
  'frontmatter-schema': frontmatterSchema,
  'link-integrity': linkIntegrity,
  'file-population': filePopulation,
  'gate-meta': gateMeta,
  'id-integrity': idIntegrity,
  'render-freshness': renderFreshness,
  'register-schema': registerSchema,
  'self-declared-closure': selfDeclaredClosure,
  'filename-schema': filenameSchema,
  'cross-reference': crossReference,
  'git-status-reconcile': gitStatusReconcile,
  'computed-claim': computedClaim,
  'term-ownership': termOwnership,
  'rule-propagation': rulePropagation,
  'git-state': gitState,
  'merge-driver-check': mergeDriverCheck,
  'board-reconcile': boardReconcile,
  'changelog-freshness': changelogFreshness,
  'change-requires-file': changeRequiresFile,
};

/**
 * Engines named in a gate table but not implemented here. Reported by name and
 * treated as blocking — never as a pass.
 *
 * This is the single most dangerous failure this tool could have: a registry of
 * 31 gates reporting green because 25 of them do nothing. rift-forge's rule
 * generalises exactly — *we do not land on an unknown.*
 */
export function isImplemented(engine: string): boolean {
  return engine in ENGINES;
}
