import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { walk } from './glob.ts';

export type Harness = 'claude' | 'copilot' | 'cursor' | 'agents-md';

export interface Rule {
  file: string;
  description?: string;
  paths: string[];
  enforcement?: string;
  body: string;
}

export interface RenderEntry {
  rule: string;
  harness: Harness;
  target?: string;
  degraded?: string;
  dropped?: string[];
}

const DO_NOT_EDIT = (source: string) =>
  `Generated by \`rungs render\` from ${source}. Do not edit — your changes are overwritten.`;

/** Parse `.ai/rules/*.md`: the neutral source ADR-0001 renders from. */
export function readRules(repoRoot: string): Rule[] {
  const dir = join(repoRoot, '.ai', 'rules');
  const rules: Rule[] = [];
  let files: string[];
  try {
    files = walk(dir).filter((f) => f.endsWith('.md') && f !== 'README.md');
  } catch {
    return rules;
  }
  for (const rel of files) {
    const raw = readFileSync(join(dir, rel), 'utf8');
    const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!m) continue;
    const [, fm, body] = m;
    rules.push({
      file: rel,
      description: scalar(fm, 'description'),
      paths: list(fm, 'paths'),
      enforcement: scalar(fm, 'enforcement'),
      body: body.trim(),
    });
  }
  return rules;
}

function scalar(fm: string, key: string): string | undefined {
  const folded = fm.match(new RegExp(`^${key}:\\s*>-?\\s*\\n([\\s\\S]*?)(?=\\n\\S|$)`, 'm'));
  if (folded) return folded[1].split('\n').map((l) => l.trim()).filter(Boolean).join(' ');
  const plain = fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'));
  return plain?.[1].trim().replace(/^["']|["']$/g, '');
}

function list(fm: string, key: string): string[] {
  const block = fm.match(new RegExp(`^${key}:\\s*\\n((?:\\s*-\\s*.+\\n?)+)`, 'm'));
  if (!block) return [];
  return [...block[1].matchAll(/^\s*-\s*(.+)$/gm)].map((m) => m[1].trim().replace(/^["']|["']$/g, ''));
}

/**
 * Emit one rule into one harness's dialect. Full bodies, never pointers: a
 * wrapper that references a shared file relies on the harness following the
 * reference, and only some do. A rule that does not load is worth nothing.
 */
export function renderRule(rule: Rule, harness: Harness): { target: string; content: string; dropped: string[] } | { degraded: string } {
  const stem = rule.file.replace(/\.md$/, '');
  const source = `.ai/rules/${rule.file}`;
  const dropped: string[] = [];

  if (harness === 'claude') {
    // No description field in a Claude rule; the routing is done by `paths`.
    if (rule.description) dropped.push('description');
    const fm = rule.paths.length ? `paths:\n${rule.paths.map((p) => `  - "${p}"`).join('\n')}\n` : '';
    return {
      target: `.claude/rules/${stem}.md`,
      content: `---\n${fm}---\n\n<!-- ${DO_NOT_EDIT(source)} -->\n\n${rule.body}\n`,
      dropped,
    };
  }

  if (harness === 'copilot') {
    const applyTo = rule.paths.length ? rule.paths.join(', ') : '**/*';
    const desc = rule.description ? `description: '${rule.description.replace(/'/g, "''")}'\n` : '';
    return {
      target: `.github/instructions/${stem}.instructions.md`,
      content: `---\n${desc}applyTo: '${applyTo}'\n---\n\n<!-- ${DO_NOT_EDIT(source)} -->\n\n${rule.body}\n`,
      dropped,
    };
  }

  if (harness === 'cursor') {
    // `.mdc` is required — a plain .md in .cursor/rules is ignored entirely.
    const desc = rule.description ? `description: ${rule.description}\n` : '';
    const globs = rule.paths.length ? `globs: ${rule.paths.join(',')}\n` : '';
    return {
      target: `.cursor/rules/${stem}.mdc`,
      content: `---\n${desc}${globs}alwaysApply: ${rule.paths.length === 0}\n---\n\n<!-- ${DO_NOT_EDIT(source)} -->\n\n${rule.body}\n`,
      dropped,
    };
  }

  // AGENTS.md-only harnesses have no glob scoping at all. Degrade explicitly
  // and report it — never drop a rule silently.
  const prefix = commonDirPrefix(rule.paths);
  if (prefix) {
    return {
      target: `${prefix}/AGENTS.md`,
      content: `<!-- ${DO_NOT_EDIT(source)} -->\n\n${rule.body}\n`,
      dropped: ['description', 'paths (directory-scoped instead of glob)'],
    };
  }
  return {
    degraded: `routing-only: globs do not share a directory prefix, so root AGENTS.md gets a pointer to ${source}`,
  };
}

function commonDirPrefix(paths: string[]): string | null {
  if (!paths.length) return null;
  const dirs = paths.map((p) => p.split('/').filter((s) => !s.includes('*')).join('/')).filter(Boolean);
  if (dirs.length !== paths.length) return null;
  const first = dirs[0];
  return dirs.every((d) => d === first) && first.includes('/') ? first : null;
}

export function render(repoRoot: string, harnesses: Harness[]): RenderEntry[] {
  const rules = readRules(repoRoot);
  const entries: RenderEntry[] = [];
  const routingOnly: Rule[] = [];

  for (const rule of rules) {
    for (const harness of harnesses) {
      const out = renderRule(rule, harness);
      if ('degraded' in out) {
        entries.push({ rule: rule.file, harness, degraded: out.degraded });
        if (harness === 'agents-md') routingOnly.push(rule);
        continue;
      }
      const full = join(repoRoot, out.target);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, out.content);
      entries.push({ rule: rule.file, harness, target: out.target, dropped: out.dropped });
    }
  }

  // The report said root AGENTS.md "gets a pointer" and nothing wrote one — a
  // degradation notice that was itself a silent drop, in the function whose
  // whole job is not to have those. Written now, as a managed block.
  writeRoutingBlock(repoRoot, routingOnly, harnesses);
  return entries;
}

function writeRoutingBlock(repoRoot: string, rules: Rule[], harnesses: Harness[]) {
  if (!harnesses.includes('agents-md')) return;
  const target = join(repoRoot, 'AGENTS.md');
  if (!existsSync(target)) return;
  const begin = '<!-- rungs:begin rules-routing -->';
  const end = '<!-- rungs:end rules-routing -->';

  const body = rules.length
    ? [
        begin,
        '## Rules for specific paths',
        '',
        'This harness has no glob scoping, so these load only if you open them. **Read the one that',
        'matches what you are editing before editing broadly.**',
        '',
        ...rules.map((r) => `- \`${r.paths.join('\`, \`')}\` → [\`.ai/rules/${r.file}\`](.ai/rules/${r.file})`),
        end,
      ].join('\n')
    : '';

  const existing = readFileSync(target, 'utf8');
  const beginRe = /^[ \t]*<!--\s*rungs:begin rules-routing\s*-->[ \t]*$/m;
  const endRe = /^[ \t]*<!--\s*rungs:end rules-routing\s*-->[ \t]*$/m;
  const b = existing.match(beginRe);
  const e = existing.match(endRe);
  if (b && e && b.index !== undefined && e.index !== undefined) {
    const next = existing.slice(0, b.index) + body.trim() + existing.slice(e.index + e[0].length);
    writeFileSync(target, body ? next : next.replace(/\n{3,}/g, '\n\n'));
    return;
  }
  if (body) writeFileSync(target, `${existing.replace(/\n+$/, '\n')}\n${body}\n`);
}

/**
 * ADR-0001: a render that quietly dropped a rule reads identically to one that
 * had nothing to drop, so every degradation lands here.
 */
export function writeReport(repoRoot: string, entries: RenderEntry[], harnesses: Harness[], stamp: string): string {
  const lines = [
    '# Render report',
    '',
    `> Generated by \`rungs render\` on ${stamp}. Do not edit.`,
    '',
    `Harnesses: ${harnesses.join(', ')}`,
    '',
    '| Rule | Harness | Emitted | Dropped / degraded |',
    '| --- | --- | --- | --- |',
  ];
  for (const e of entries) {
    const lost = e.degraded ?? (e.dropped?.length ? e.dropped.join(', ') : '—');
    lines.push(`| \`${e.rule}\` | ${e.harness} | ${e.target ? `\`${e.target}\`` : '**not emitted**'} | ${lost} |`);
  }
  const degraded = entries.filter((e) => e.degraded).length;
  const lossy = entries.filter((e) => e.dropped?.length).length;
  lines.push(
    '',
    `${entries.length} renderings · ${lossy} lost a field · ${degraded} degraded.`,
    '',
    'A field listed as dropped is one the target harness has no way to express. It is recorded',
    'here rather than silently discarded, so a repo can see what its harness choice costs it.',
    '',
  );
  const content = lines.join('\n');
  writeFileSync(join(repoRoot, '.ai', 'render-report.md'), content);
  return content;
}
